- name: use Openstack command line clients to check if Security Group exists
  shell: openstack --os-cloud "os_{{ pop }}_{{ proj }}" security group list
  register: os_secgrp

- name: create a new Security Group for SSH connections
  os_security_group:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: "vm-secgrp"
    description: SSH ports
  when: os_secgrp.stdout.find('vm-secgrp') == -1 or os_secgrp.stdout.find('ssh-secgrp') == -1

- name: create a Security Rule on that group to allow SSH connection from ANY machine
  os_security_group_rule:
    cloud: "os_{{ pop }}_{{ proj }}"
    security_group: "vm-secgrp"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  when: os_secgrp.stdout.find('vm-secgrp') == -1 or os_secgrp.stdout.find('ssh-secgrp') == -1

