---

- name: deploying Infrastructure Abstractor VIM Adaptor (Docker container)
  docker_container:
    name: son-sp-infrabstract
    image: "sonatanfv/son-sp-infrabstract:{{ ver }}"
    state: started
    env:
      broker_host: "son-broker"
      broker_uri: "amqp://guest:guest@son-broker:5672/%2F"
      repo_host: "son-postgres"
      repo_port: "5432"
      repo_user: "sonatatest"
      repo_pass: "sonata"
      network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-sp-infrabstract

