---

- name: deploying Infrastructure Abstractor WIM Adaptor (Docker container)
  docker_container:
    name: wim-adaptor
    image: "sonatanfv/wim-adaptor:{{ ver }}"
    state: started
    env:
      broker_host: "son-broker"
      broker_uri: "amqp://guest:guest@son-broker:5672/%2F"
      repo_host: "son-postgres"
      repo_port: "5432"
      repo_user: "sonatatest"
      repo_pass: "sonata"
      network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - wim-adaptor

