---

- debug: msg="##### SP MONIT DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

# Running the Sonata MONITORY Docker Images

- include_tasks: monit/pushgw.yml
- include_tasks: monit/prometheus.yml
- include_tasks: monit/monitmgr.yml
- include_tasks: monit/probe.yml
