---
- debug: msg="##### SP PGSQL-MONITORING DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: deploy a PostgreSQL database server as a Container
  docker_container:
    name: son-monitor-postgres
    image: ntboes/postgres-uuid
    env:
      #POSTGRES_DB=monitoring
      #POSTGRES_USER=monitoringuser
      #POSTGRES_PASSWORD=sonata
      POSTGRES_DB: "{{ dbname }}"
      POSTGRES_USER: "{{ dbuser }}"
      POSTGRES_PASSWORD: "{{ upassword }}"
    state: started
    command: postgres -p 5433
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-monitor-postgres
          - postgsql
    published_ports: 5433:5432
