# CENTOS 7
- name: installing EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: installing JDK
  yum: name=java-1.8.0-openjdk state=present update_cache=yes

- name: Installing Jenkins YUM GPG key
  rpm_key: state=present key=https://jenkins-ci.org/redhat/jenkins-ci.org.key

#- name: Installing Jenkins YUM repo
#  copy: src=jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
#  sudo: yes

- name: install Jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644

- name: installing Jenkins package
  yum: name=jenkins state=latest update_cache=yes

- name: starting Jenkins service
  service: name=jenkins state=started

# Manage FW

#- name: install firewalld Python dependencies
#  yum: name={{ item }} state=present
#  with_items:
#  - python-pip
#  - python-devel
#  - python-setuptools
#  - policycoreutils

- name: install 'firewalld' to manage arbitrary ports/services
  yum: name=firewalld state=latest

- name: start 'firewalld' service (replaces 'iptables' in CentOS 7)
  service: name=firewalld state=started

- name: open Jenkins listening port at fw
  firewalld: port=8080/tcp permanent=true state=enabled
