---

- hosts: "{{ target | default ('localhost')  }}"
  become: true
  connection: ssh
  vars:
    target: localhost
    plat: sp
    pop: alabs
    domain_name: sonata-nfv.eu
    public_ip: localhost
    plat_hostname: "{{ lookup('env','HOSTNAME') }}"
  pre_tasks:
    - debug: msg="##### START-SP-DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d%H%M') }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=r,o=r"
  roles:
    - { role: sp, ver: '{{ ver }}' }

