---

# Redhat

- name: clean cache info
  command: 'yum clean all'

- name:  upgrade all packages to the latest version
  yum: name='*' state=latest update_cache=yes

- name: install useful operating system tools
  yum: name={{ item }}
  with_items:
  - sysstat
  - nmap
  - lsof
  - tree
  - htop
