vm_user: ubuntu
image: xenial-cldimg
flavor: m1.small
security_groups: "{{ plat }}-secgrp"
availability_zone: nova
region_name: RegionOne
key_name: son-install
int_net_id: "3ef0b481-8c8c-49c7-88f5-10e4d8c5612f" # QUAL

